### ISSUE TITLE
Linux和windows都不能编译通过

### ISSUE THREAD

**Issue by fdkeylabhu** [rogerzhu/buwen#1]
是只能在macos使用嘛

**Comment by rogerzhu** [comment]
我来看看咋回事，可能是我想当然了，没在linux上真试过，windows上估计是编译不过，create file那些API没有用windows上的

**Comment by rogerzhu** [comment]
啊！我居然漏了一个memory头文件，十分感谢，已经可以在linux上编过了，大意了。
